/**
 * Eufraat menukaart — gestructureerd vanuit de Bistroo-pagina.
 * Prijzen in centen. Foto's nog leeg — eigenaar uploadt via staff-app.
 * Bron: https://www.bistroo.nl/geleen/restaurants/eufraat (juni 2026)
 */

import type { MenuCategory, MenuItem, ModifierGroup, Restaurant } from "./index";

const SAUS_OPTIES = [
  { id: "knoflook", name: "Knoflooksaus", priceDelta: 0 },
  { id: "andalouse", name: "Andalouse", priceDelta: 0 },
  { id: "cocktail", name: "Cocktail", priceDelta: 0 },
  { id: "sambal", name: "Sambal", priceDelta: 0 },
  { id: "chili", name: "Chilisaus", priceDelta: 0 },
  { id: "mayo", name: "Mayonaise", priceDelta: 0 },
  { id: "curry", name: "Curry", priceDelta: 0 },
  { id: "samurai", name: "Samurai", priceDelta: 0 },
];

const SAUS_GROUP: ModifierGroup = {
  id: "saus",
  name: "Saus naar keuze",
  required: true,
  min: 1,
  max: 1,
  options: SAUS_OPTIES,
};

const PASTA_GROUP: ModifierGroup = {
  id: "pasta",
  name: "Pasta",
  required: true,
  min: 1,
  max: 1,
  options: [
    { id: "spaghetti", name: "Spaghetti", priceDelta: 0 },
    { id: "macaroni", name: "Macaroni", priceDelta: 0 },
  ],
};

const KAPSALON_SIZE: ModifierGroup = {
  id: "size",
  name: "Maat",
  required: true,
  min: 1,
  max: 1,
  options: [
    { id: "klein", name: "Klein", priceDelta: 0 },
    { id: "groot", name: "Groot", priceDelta: 200 },
  ],
};

const FRIET_SIZE: ModifierGroup = {
  id: "size",
  name: "Maat",
  required: true,
  min: 1,
  max: 1,
  options: [
    { id: "klein", name: "Klein", priceDelta: 0 },
    { id: "groot", name: "Groot", priceDelta: 100 },
  ],
};

export const SEED_RESTAURANT: Restaurant = {
  id: "eufraat",
  name: "Eufraat",
  address: "Rijksweg Centrum 38",
  postcode: "6161 EG",
  city: "Geleen",
  phone: "+31464106745",
  timezone: "Europe/Amsterdam",
  pickupEnabled: true,
  deliveryEnabled: true,
  prepTimeMinutes: 45,
  pauseUntil: null,
  openingHours: {
    mon: {
      pickup: [{ open: "15:30", close: "00:50", endsNextDay: true }],
      delivery: [{ open: "16:00", close: "00:45", endsNextDay: true }],
    },
    tue: { pickup: [], delivery: [] },
    wed: {
      pickup: [{ open: "15:30", close: "00:50", endsNextDay: true }],
      delivery: [{ open: "16:00", close: "00:45", endsNextDay: true }],
    },
    thu: {
      pickup: [{ open: "15:30", close: "00:50", endsNextDay: true }],
      delivery: [{ open: "16:00", close: "00:45", endsNextDay: true }],
    },
    fri: {
      pickup: [{ open: "15:30", close: "00:50", endsNextDay: true }],
      delivery: [{ open: "16:00", close: "00:45", endsNextDay: true }],
    },
    sat: {
      pickup: [{ open: "15:30", close: "00:50", endsNextDay: true }],
      delivery: [{ open: "16:00", close: "00:45", endsNextDay: true }],
    },
    sun: {
      pickup: [{ open: "15:30", close: "00:50", endsNextDay: true }],
      delivery: [{ open: "16:00", close: "00:45", endsNextDay: true }],
    },
  },
  deliveryZones: [
    { postcodePrefix: "6161", fee: 200, minOrder: 1500 },
    { postcodePrefix: "6162", fee: 250, minOrder: 1500 },
    { postcodePrefix: "6163", fee: 300, minOrder: 1500 },
    { postcodePrefix: "6164", fee: 300, minOrder: 2000 },
    { postcodePrefix: "6165", fee: 350, minOrder: 2000 },
    { postcodePrefix: "6166", fee: 350, minOrder: 2000 },
  ],
};

export const SEED_CATEGORIES: MenuCategory[] = [
  { id: "pizzas", name: "Pizza's", description: "", order: 1, visible: true },
  {
    id: "gevulde-pizzas",
    name: "Gevulde pizza's",
    description: "Geserveerd met een bakje saus.",
    order: 2,
    visible: true,
  },
  {
    id: "pastas",
    name: "Pasta's overbakken met kaas",
    description: "Keuze uit spaghetti of macaroni.",
    order: 3,
    visible: true,
  },
  {
    id: "kapsalon",
    name: "Kapsalon",
    description: "Vlees met salade, friet, gesmolten kaas en saus.",
    order: 4,
    visible: true,
  },
  {
    id: "schotels",
    name: "Schotel specialiteiten",
    description: "Geserveerd met friet, salade, brood en saus naar keuze.",
    order: 5,
    visible: true,
  },
  { id: "durum", name: "Dürüm", description: "", order: 6, visible: true },
  {
    id: "hamburgers",
    name: "Hamburgers",
    description: "",
    order: 7,
    visible: true,
  },
  {
    id: "broodjes",
    name: "Broodjes",
    description: "",
    order: 8,
    visible: true,
  },
  { id: "menus", name: "Menu's", description: "", order: 9, visible: true },
  { id: "friet", name: "Friet", description: "", order: 10, visible: true },
  { id: "snacks", name: "Snacks", description: "", order: 11, visible: true },
  {
    id: "bijgerechten",
    name: "Bijgerechten",
    description: "",
    order: 12,
    visible: true,
  },
  { id: "extras", name: "Extra's", description: "", order: 13, visible: true },
  { id: "dranken", name: "Dranken", description: "", order: 14, visible: true },
];

// Helper voor minder boilerplate per item.
const item = (
  id: string,
  name: string,
  description: string,
  priceEur: number,
  opts: Partial<MenuItem> = {},
): MenuItem => ({
  id,
  name,
  description,
  price: Math.round(priceEur * 100),
  photo: null,
  allergens: [],
  halal: true,
  visible: true,
  soldOut: false,
  order: 0,
  modifierGroups: [],
  ...opts,
});

export const SEED_ITEMS: Record<string, MenuItem[]> = {
  pizzas: [
    item("pizza-half-half", "Pizza half/half", "Kies twee soorten pizza's!", 14.5),
    item("kinderpizza", "Kinderpizza", "Tomatensaus, kaas, mozzarella en oregano.", 8.5),
    item("pizza-margherita", "Pizza Margherita", "Tomatensaus, kaas, mozzarella en oregano.", 10.0),
    item("pizza-napolitano", "Pizza napolitano", "Tomatensaus, kaas en ansjovis.", 11.5),
    item("pizza-prosciutto", "Pizza prosciutto", "Tomatensaus, mozzarella en ham.", 12.0),
    item("pizza-salami", "Pizza salami", "Tomatensaus, kaas en salami.", 12.0),
    item("pizza-mengen", "Pizza mengen", "Tomatensaus, mozzarella, ham, salami, spinazie en ei.", 13.0),
    item("pizza-funghi", "Pizza funghi", "Tomatensaus, kaas en champignons.", 11.0),
    item("pizza-peperoni", "Pizza peperoni", "Tomatensaus, mozzerella, salami, uien en peperoni.", 12.5),
    item("pizza-siciliana", "Pizza Siciliana", "Tomatensaus, mozzarella, kappertjes, olijven en ansjovis.", 13.0),
    item("pizza-fantastica", "Pizza fantastica", "Tomatensaus, mozzarella, champignons en ham.", 12.0),
    item("pizza-popeye", "Pizza popeye", "Tomatensaus, mozzarella, verste tomaat, spinazie en fetakaas.", 12.5),
    item("pizza-diavola", "Pizza diavola", "Tomatensaus, mozzarella, orginele chorizo, salami en uien.", 13.0),
    item("pizza-lombardo", "Pizza lombardo", "Tomatensaus, mozzarella, ham, champignons en ei.", 13.0),
    item("pizza-stagioni", "Pizza stagioni", "Tomatensaus, mozzarella, champignons, ham, salami en paprika.", 13.0),
    item("pizza-capricciosa", "Pizza capricciosa", "Tomatensaus, mozzarella, champignons, ham, salami en artisjokken.", 13.0),
    item("pizza-vegetaria", "Pizza vegetaria", "Tomatensaus, mozzarella, champignons, uien, paprika, artisjokken en olijven.", 13.0),
    item("pizza-kebab", "Pizza kebab", "Tomatensaus, mozzarella, döner kebab vlees en uien.", 13.0),
    item("pizza-pollo", "Pizza pollo", "Tomatensaus, mozzarella, champignons, kip en paprika.", 13.5),
    item("pizza-bolognese", "Pizza bolognese", "Tomatensaus, mozzarella, rundergehakt, paprika en uien.", 13.0),
    item("pizza-shoarma", "Pizza shoarma", "Tomatensaus, mozzarella, shoarmavlees, uien en paprika.", 13.5),
    item("pizza-tonno", "Pizza tonno", "Tomatensaus, mozzarella, tonijn en uien.", 13.0),
    item("pizza-sultana", "Pizza sultana", "Tomatensaus, mozzarella, pikante Turkse worst, champignons en ei.", 13.5),
    item("pizza-angolino", "Pizza Angolino", "Tomatensaus, mozzarella, vier soorten kaas en spinazie.", 13.5),
    item("pizza-verona", "Pizza Verona", "Tomatensaus, mozzarella, champignons, uien, ham, paprika en gehakt.", 13.5),
    item("pizza-hawai", "Pizza Hawaï", "Tomatensaus, mozzarella, ham en ananas.", 13.0),
    item("pizza-al-formaggio", "Pizza al formaggio", "Tomatensaus en vier soorten kaas.", 13.5),
    item("pizza-pollo-hot", "Pizza pollo hot", "Tomatensaus, mozzarella, paprika, champignons en pittig gekruid kippenvlees.", 13.5),
    item("pizza-welat", "Pizza Welat", "Tomatensaus, mozzarella, pittig gekruid gehakt en salami.", 13.0),
    item("pizza-quattro-kebab", "Pizza quattro kebab", "Tomatensaus, mozzarella en vier soorten vlees.", 15.0),
    item("pizza-tigris", "Pizza Tigris", "Tomatensaus, mozzarella, ham, salami, champignons, paprika en ui.", 13.5),
    item("pizza-international", "Pizza international", "Tomatensaus, mozzarella, uien, shoarma, peperoni en verse knoflook.", 13.5),
    item("pizza-frutti-di-mare", "Pizza frutti di mare", "Tomatensaus, mozzarella en zeevruchten.", 14.5),
    item("pizza-taco", "Pizza taco", "Tomatensaus, mozzarella, rundergehakt, ijsbergsla, komkommer en tomaat.", 14.0),
    item("lahmacun", "Lahmacun", "Turkse pizza met salade.", 6.0),
    item("pizza-kebab-speciaal", "Pizza kebab speciaal", "Döner met champignons, paprika, uien, tomatensaus en kaas.", 13.5),
  ],
  "gevulde-pizzas": [
    item("calzone", "Calzone", "Gevulde pizza met tomatensaus, kaas champignons, gehakt etc.", 14.0),
    item("kip-calzone", "Kip calzone", "Gevulde pizza met tomatensaus, kaas, gekruid kippenvlees, paprika, champignons en uien.", 15.0),
    item("calzone-eufraat-1", "Calzone Eufraat 1", "Gevulde pizza met tomatensaus, kaas, champignons, salami, shoarmavlees, ham, uien, paprika, mosselen, garnalen en tonijn.", 16.0),
    item("calzone-eufraat-2", "Calzone Eufraat 2", "Gevulde pizza met tomatensaus, kaas, paprika, champignons, shoarmavlees, artisjok, uien en ham.", 15.0),
    item("calzone-doner-kebab", "Calzone döner kebab", "Gevulde pizza met tomatensaus, kaas, döner en groente.", 15.0),
  ],
  pastas: [
    item("pasta-bolognese", "Pasta alla bolognese", "Met gehakt en tomatensaus.", 11.5, { modifierGroups: [PASTA_GROUP] }),
    item("pasta-frutti-di-mare", "Pasta frutti di mare", "Met tomatensaus, knoflook en zeevruchten.", 13.5, { modifierGroups: [PASTA_GROUP] }),
    item("pasta-vegetaria", "Pasta vegetaria", "Met tomatensaus en groenten.", 11.5, { modifierGroups: [PASTA_GROUP] }),
    item("lasagna-chef", "Lasagna alla chef", "Specialiteit van de chefkok: lasagne geserveerd met brood en salade. Niet halal.", 11.5, { halal: false }),
    item("lasagna-ham", "Lasagna met ham", "Met ham. Niet halal.", 12.0, { halal: false }),
  ],
  kapsalon: [
    item("kapsalon-doner", "Kapsalon döner", "Keuze uit een kleine of grote kapsalon.", 11.5, { modifierGroups: [KAPSALON_SIZE] }),
    item("kapsalon-shoarma", "Kapsalon shoarma", "Keuze uit een kleine of grote kapsalon.", 12.0, { modifierGroups: [KAPSALON_SIZE] }),
    item("kapsalon-kipfilet", "Kapsalon kipfilet", "Keuze uit een kleine of grote kapsalon.", 12.0, { modifierGroups: [KAPSALON_SIZE] }),
    item("kapsalon-kip-kebab", "Kapsalon kip kebab", "Keuze uit een kleine of grote kapsalon.", 11.5, { modifierGroups: [KAPSALON_SIZE] }),
  ],
  schotels: [
    item("shoarma-klein", "Shoarma klein schotel", "Shoarma klein schotel", 12.0, { modifierGroups: [SAUS_GROUP] }),
    item("shoarma-groot", "Shoarma groot schotel", "Shoarma groot schotel", 14.0, { modifierGroups: [SAUS_GROUP] }),
    item("shoarma-super-groot", "Shoarma super groot schotel", "Met extra pita en extra vlees.", 15.5, { modifierGroups: [SAUS_GROUP] }),
    item("tagin-klein", "Tagin schotel klein", "Shoarmavlees, uien, paprika, champignons en kaas.", 14.0, { modifierGroups: [SAUS_GROUP] }),
    item("tagin-groot", "Tagin schotel groot", "Shoarmavlees, uien, paprika, champignons en kaas.", 15.5, { modifierGroups: [SAUS_GROUP] }),
    item("gyros-klein", "Gyros schotel klein", "Met caciksaus.", 12.5, { modifierGroups: [SAUS_GROUP] }),
    item("gyros-groot", "Gyros schotel groot", "Met caciksaus.", 14.5, { modifierGroups: [SAUS_GROUP] }),
    item("doner-klein", "Döner kebab klein schotel", "100% lamsvlees.", 12.0, { modifierGroups: [SAUS_GROUP] }),
    item("doner-groot", "Döner kebab groot schotel", "100% lamsvlees.", 13.5, { modifierGroups: [SAUS_GROUP] }),
    item("kipsate-klein", "Kipsaté klein schotel", "Kipsaté klein schotel", 13.5, { modifierGroups: [SAUS_GROUP] }),
    item("kipsate-groot", "Kipsaté groot schotel", "Kipsaté groot schotel", 14.5, { modifierGroups: [SAUS_GROUP] }),
    item("kipsjasliek-klein", "Kipsjasliek klein schotel", "Kipfilet met uien en paprika.", 13.0, { modifierGroups: [SAUS_GROUP] }),
    item("kipsjasliek-groot", "Kipsjasliek groot schotel", "Kipfilet met uien en paprika.", 15.0, { modifierGroups: [SAUS_GROUP] }),
    item("kipschotel-klein", "Kipschotel klein", "Kipschotel klein", 12.0, { modifierGroups: [SAUS_GROUP] }),
    item("kipschotel-groot", "Kipschotel groot", "Kipschotel groot", 13.5, { modifierGroups: [SAUS_GROUP] }),
    item("shoarma-spec-klein", "Shoarma speciaal klein schotel", "Shoarmavlees met champignons, paprika en uien.", 13.5, { modifierGroups: [SAUS_GROUP] }),
    item("shoarma-spec-groot", "Shoarma speciaal groot schotel", "Shoarmavlees met champignons, paprika en uien.", 15.5, { modifierGroups: [SAUS_GROUP] }),
    item("hot-chicken-klein", "Hot chicken klein schotel", "Pittig gekruide kipfilet, champignons, uien en paprika.", 13.5, { modifierGroups: [SAUS_GROUP] }),
    item("hot-chicken-groot", "Hot chicken groot schotel", "Pittig gekruide kipfilet, champignons, uien en paprika.", 15.5, { modifierGroups: [SAUS_GROUP] }),
    item("spareribs-klein", "Spareribs klein schotel", "Vier stuks, niet halal.", 14.5, { halal: false, modifierGroups: [SAUS_GROUP] }),
    item("spareribs-groot", "Spareribs groot schotel", "Zes stuks, niet halal.", 17.0, { halal: false, modifierGroups: [SAUS_GROUP] }),
    item("adana-kebab", "Adana kebab 3st.", "Pittig gekruid gehakt", 11.5, { modifierGroups: [SAUS_GROUP] }),
    item("kipfilet-klein", "Kipfilet klein schotel", "Gekruide kipfilet.", 13.0, { modifierGroups: [SAUS_GROUP] }),
    item("kipfilet-groot", "Kipfilet groot schotel", "Gekruide kipfilet.", 14.5, { modifierGroups: [SAUS_GROUP] }),
    item("eufraat-1persoon", "Eufraat 1 persoon schotel", "Diverse vleesspecialiteiten.", 19.0, { modifierGroups: [SAUS_GROUP] }),
    item("lamskoteletten", "Lamskoteletten schotel", "Drie stuks.", 18.5, { modifierGroups: [SAUS_GROUP] }),
  ],
  durum: [
    item("durum-kipfilet", "Kipfilet dürüm", "Gekruide kipfilet.", 9.5),
    item("durum-hot-chicken", "Hot chicken dürüm", "Pittig gekruide kipfilet, champignons, paprika en uien.", 10.5),
    item("durum-kipdoner", "Kipdöner dürüm", "100% kippenvlees.", 8.0),
    item("durum-doner", "Döner dürüm", "Döner dürüm", 8.0),
    item("durum-gyros", "Gyros dürüm", "Met cacik.", 9.5),
    item("durum-shoarma-spec", "Shoarma speciaal dürüm", "Shoarma met champignons, paprika en uien.", 10.0),
    item("durum-shoarma", "Shoarma dürüm", "Shoarma dürüm", 8.5),
    item("durum-vegetaria", "Vegetaria dürüm", "Met onder andere ei en feta kaas.", 7.5),
    item("durum-kofte", "Köfte dürüm", "Köfte dürüm", 7.5),
  ],
  hamburgers: [
    item("hamburger", "Hamburger", "Met mayonaise, curry en uien.", 5.5),
    item("hamburger-spec", "Hamburger speciaal", "Met groenten, uien, mayonaise en curry.", 6.0),
    item("cheeseburger", "Cheeseburger", "Met kaas.", 6.0),
    item("reuze-american", "Reuze American burger", "Met sla en andalouse saus. Niet halal.", 6.5, { halal: false }),
  ],
  broodjes: [
    item("brood-shoarma", "Broodje shoarma", "Broodje shoarma", 8.0),
    item("brood-shoarma-kaas", "Broodje shoarma met kaas", "Broodje shoarma met kaas", 8.5),
    item("brood-reuze-shoarma", "Broodje reuze shoarma", "Extra vlees.", 10.0),
    item("brood-gyros", "Broodje gyros", "Met cacik.", 9.0),
    item("brood-kipfilet", "Broodje kipfilet", "Broodje kipfilet", 9.0),
    item("brood-doner", "Broodje döner kebab", "100% lamsvlees, verse salade en Turks brood.", 7.0),
    item("brood-kip-doner", "Broodje kip döner kebab", "100% kippenvlees.", 7.0),
    item("brood-shoarma-spec", "Broodje shoarma speciaal", "Met shoarma, champignons, paprika en uien.", 9.0),
    item("brood-hot-chicken", "Broodje hot chicken", "Pittig gekruide kipfilet, champignons, uien en paprika.", 10.0),
    item("brood-kaas", "Broodje kaas", "Pitabroodje met gesmolten kaas.", 3.0),
    item("brood-doner-groot", "Broodje döner groot", "Half Turks brood.", 13.0),
    item("brood-kip-groot", "Broodje kip groot", "Broodje kip groot", 13.0),
    item("doner-box", "Doner Box", "Doner Box", 8.5),
  ],
  menus: [
    item("menu-1-kinder", "Menu 1: kindermenu", "Kipnuggets of kip fingers, friet, appelmoes en Capri Sun.", 8.5),
    item("menu-2-durum", "Menu 2: dürüm menu", "Dürüm döner of dürüm kip, friet en pepsi.", 12.0),
    item("menu-3-broodje", "Menu 3: broodje menu", "Broodje döner of broodje kip, friet en pepsi.", 11.5),
    item("menu-4-hamburger", "Menu 4: hamburger menu", "Hamburger, friet en pepsi.", 11.5),
    item("menu-5-lahmacun", "Menu 5: lahmacun menu", "Lahmacun, friet en pepsi.", 11.0),
  ],
  friet: [
    item("friet", "Friet", "Keuze uit een kleine of een grote friet.", 3.0, { modifierGroups: [FRIET_SIZE] }),
    item("friet-mayo", "Friet mayonaise", "Keuze uit een kleine of een grote friet.", 4.0, { modifierGroups: [FRIET_SIZE] }),
    item("friet-spec", "Friet speciaal", "Keuze uit een kleine of een grote friet.", 4.5, { modifierGroups: [FRIET_SIZE] }),
    item("friet-sate", "Friet saté", "Keuze uit een kleine of een grote friet.", 4.5, { modifierGroups: [FRIET_SIZE] }),
  ],
  snacks: [
    item("kaassouffle", "Kaassouflé", "Kaassouflé", 2.5),
    item("frikandel", "Frikandel", "Niet halal.", 2.5, { halal: false }),
    item("frikandel-spec", "Frikandel speciaal", "Frikandel speciaal", 3.0, { halal: false }),
    item("bitterballen", "Bitterballen", "Zes stuks, niet halal.", 3.5, { halal: false }),
    item("sitostick", "Sitostick", "Sitostick", 3.7),
    item("kipfingers", "Kipfingers", "Zes stuks.", 3.5),
    item("kipnuggets", "Kipnuggets", "Zes stuks.", 3.5),
    item("bamiblok", "Bamiblok", "Bamiblok", 2.5),
    item("gehaktbal", "Gehaktbal", "Niet halal.", 2.9, { halal: false }),
    item("mexicano", "Mexicano", "Niet halal.", 2.9, { halal: false }),
  ],
  bijgerechten: [
    item("salade-gemengd", "Gemengde salade", "Gemengde salade met onder andere sla, tomaten en komkommer.", 4.0),
    item("salade-eufraat", "Insalata Eufraat", "Gemengde salade, ham, olijven en fetakaas.", 8.0),
    item("salade-tonno", "Insalata tonno", "Gemengde salade met tonijn.", 7.0),
    item("salade-griekse", "Griekse salade", "Gemengde salade, fetakaas, olijven, knoflook en uien.", 7.0),
    item("salade-coban", "Coban salade", "Pittig gekruide uien, komkommer en tomaat.", 6.0),
    item("salade-tomaat", "Tomatensalade", "Gemengde salade en rode uien.", 5.5),
    item("salade-komkommer", "Komkommersalade", "Komkommer gemengd met een speciale saus.", 5.0),
    item("stokbrood", "Stokbrood met kruidenboter", "Stokbrood met kruidenboter", 4.5),
  ],
  extras: [
    item("olijven", "Portie olijven", "Portie olijven", 3.5),
    item("peperoni", "Portie peperoni", "Portie peperoni", 3.5),
    item("tzatziki", "Tzatziki", "Tzatziki", 2.5),
    item("fetakaas", "Portie fetakaas", "Portie fetakaas", 3.5),
    item("ex-knoflook", "Extra knoflooksaus", "Extra knoflooksaus", 0.8),
    item("ex-andalouse", "Extra andalouse saus", "Extra andalouse saus", 0.8),
    item("ex-cocktail", "Extra cocktailsaus", "Extra cocktailsaus", 0.8),
    item("ex-sambal", "Extra sambalsaus", "Extra sambalsaus", 0.8),
    item("ex-chili", "Extra chilisaus", "Extra chilisaus", 0.8),
    item("ex-mayo", "Extra mayonaise", "Extra mayonaise", 0.8),
    item("ex-curry", "Extra curry", "Extra curry", 0.8),
    item("ex-samurai", "Extra samurai", "Extra samurai", 0.8),
    item("ex-andalouse-2", "Extra andalouse", "Extra andalouse", 0.8),
  ],
  dranken: [
    item("d-caprisun", "Capri-Sun 200ml", "Capri-Sun 200ml", 1.5),
    item("d-cola", "Coca-Cola 330ml", "Bevat caffeine (9,6 mg/100 ml)", 2.75),
    item("d-cola-zero", "Coca-Cola zero sugar 330ml", "Bevat caffeine (10,0 mg/100 ml)", 2.75),
    item("d-cola-cherry", "Coca-Cola cherry 330ml", "Bevat caffeine (9,6 mg/100 ml)", 2.75),
    item("d-fanta-orange", "Fanta orange 330ml", "Fanta orange 330ml", 2.75),
    item("d-fanta-cassis", "Fanta cassis 330ml", "Fanta cassis 330ml", 2.75),
    item("d-fanta-exotic", "Fanta exotic 330ml", "Fanta exotic 330ml", 2.75),
    item("d-aadrink", "AA Drink 330ml", "AA Drink 330ml", 2.5),
    item("d-pepsi", "Pepsi", "Pepsi", 2.75),
    item("d-lipton-sparkling", "Lipton ice tea sparkling 330ml", "Lipton ice tea sparkling 330ml", 2.75),
    item("d-lipton-green", "Lipton ice tea green 330ml", "Lipton ice tea green 330ml", 2.75),
    item("d-redbull", "Red Bull Energy Drink 250ml", "Bevat caffeine (80,0 mg/100 ml)", 3.3),
    item("d-fanta-fles", "Fles Fanta 1500ml", "1.5 liter.", 5.0),
    item("d-cola-fles", "Fles Coca-Cola 1500ml", "1.5 liter. Bevat caffeine (9,6 mg/100 ml)", 5.0),
    item("d-energy-slammers", "Energy slammers", "Energy slammers", 2.0),
  ],
};
